#
# Rebuild and publish our base Docker images for OCaml once a week.
#

version: 2.1

executors:
  amd64:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: medium
  arm64:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: arm.medium

jobs:
  push-multi-arch:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: |
            images=$(cat digests-* | cut -f 1 | sort | uniq)
            for image in $images; do
              repo=$(echo $image | cut -d: -f1)
              manifest_args=()
              for digest in $(cat digests-* | grep $image$'\t' | cut -f2); do
                manifest_args+=( --amend $repo@$digest )
              done
              echo "Would run: docker manifest create $image $manifest_args"
            done

  build-and-save:
    parameters:
      architecture:
        type: executor
    executor: << parameters.architecture >>
    steps:
      - checkout
      - run:
          name: Build
          command: make build
      - run:
          name: Tag builds with architecture
          command: |
            arch=$(docker info -f "{{ .Architecture }}")
            cp pushme
            digests="digests-${arch}"
            for image in $(cat pushme); do
              echo -e "${image}\t$(docker image inspect -f "{{ .Id }}" ${image})"
            done
            docker save -o images-$arch.tar $(cat pushme)
      - persist_to_workspace:
          root: .
          paths:
            - digests-*
            - images-*.tar

  build-only:
    parameters:
      architecture:
        type: executor
    executor: << parameters.architecture >>
    steps:
      - checkout
      - run:
          name: Build
          command: make build

workflows:
  version: 2

  build-on-pr:
    jobs:
      - build-and-save:
          matrix:
            parameters:
              architecture: [amd64, arm64]
      - push-multi-arch:
          requires:
            - "build-and-save"

  build-and-push-on-master-push:
    jobs:
      - build-and-push:
          matrix:
            parameters:
              architecture: [amd64]  # TODO: re-introduce arm64 once we've figured out how to correctly publish a multi-arch docker image
          filters:
            branches:
              only:
                - master

  build-and-push-weekly:
    # Rebuild periodically rather than based on git changes.
    triggers:
      - schedule:
          # Run at 07:00 every Thursday, UTC.
          cron: "0 07 * * 4"
          filters:
            branches:
              only:
                - master
                - main

    jobs:
      - build-and-push:
          matrix:
            parameters:
              architecture: [amd64]  # TODO: re-introduce arm64 once we've figured out how to correctly publish a multi-arch docker image
          # Run only on these branches (each pushing different images)
          filters:
            branches:
              only:
                - master
                - main
