#
# Rebuild and publish our base Docker images for OCaml once a week.
#

version: 2.1

executors:
  amd64:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: medium
  arm64:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: arm.medium

jobs:
  push-multi-arch:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Login
          command: ./.circleci/docker-login
      - run:
          name: Create multi-arch images
          command: make create-multi-arch
      - run:
          name: Push
          command: make push

  build-and-push:
    parameters:
      architecture:
        type: executor
    executor: << parameters.architecture >>
    steps:
      - checkout
      - run:
          name: Build
          command: make build
      - run:
          name: Tag images with arch
          command: make tag-with-arch
      - persist_to_workspace:
          root: .
          paths:
            - images-*
      - run:
          name: Login
          command: ./.circleci/docker-login
      - run:
          name: Push
          command: make push

  build-only:
    parameters:
      architecture:
        type: executor
    executor: << parameters.architecture >>
    steps:
      - checkout
      - run:
          name: Build
          command: make build

workflows:
  version: 2

  build-on-pr:
    jobs:
      - build-only:
          matrix:
            parameters:
              architecture: [amd64, arm64]

  build-and-push-on-master-push:
    jobs:
      - build-and-push:
          matrix:
            parameters:
              architecture: [amd64, arm64]
          filters:
            branches:
              only:
                - master
      - push-multi-arch:
          requires: [build-and-push]
          filters:
            branches:
              only:
                - master

  build-and-push-weekly:
    # Rebuild periodically rather than based on git changes.
    triggers:
      - schedule:
          # Run at 07:00 every Thursday, UTC.
          cron: "0 07 * * 4"
          filters:
            branches:
              only:
                - master
                - main

    jobs:
      - build-and-push:
          matrix:
            parameters:
              architecture: [amd64, arm64]
          # Run only on these branches (each pushing different images)
          filters:
            branches:
              only:
                - master
                - main
      - push-multi-arch:
          requires: [build-and-push]
          # Run only on these branches (each pushing different images)
          filters:
            branches:
              only:
                - master
                - main
