#
# Rebuild and publish our base Docker images for OCaml once a week.
#

version: 2.1

executors:
  amd64:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: medium
  arm64:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: arm.medium

jobs:
  push-multi-arch:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Create and push multi-arch manifest
          command: |
            for archive in /tmp/workspace/images-*.tar; do
              echo "Loading ${archive}..."
              docker load -i $archive
            done

            for image in $(cat /tmp/workspace/digests-* | cut -f1 | sort | uniq); do
              repo=$(echo $image | cut -d: -f1)
              manifest_args=()
              for digest in $(cat /tmp/workspace/digests-* | grep ${image}$'\t' | cut -f2); do
                docker inspect $repo@$digest
                manifest_args+=( --amend "${repo}@${digest}" )
              done
              echo "Run: docker manifest create $image ${manifest_args[@]}"
              docker manifest create $image ${manifest_args[@]}
            done

  build-and-save:
    parameters:
      architecture:
        type: executor
    executor: << parameters.architecture >>
    steps:
      - checkout
      - run:
          name: Build
          command: make build
      - run:
          name: Save images
          command: |
            arch=$(docker info -f '{{ .Architecture }}')
            digests="digests-${arch}"
            rm -f $digests
            for image in $(cat pushme); do
              digest=$(docker image inspect -f '{{ .Id }}' $image)
              echo -e "${image}\t${digest}" >> $digests
            done
            docker save -o images-$arch.tar $(cat pushme)
      - persist_to_workspace:
          root: .
          paths:
            - images-*.tar
            - digests-*

  build-only:
    parameters:
      architecture:
        type: executor
    executor: << parameters.architecture >>
    steps:
      - checkout
      - run:
          name: Build
          command: make build

workflows:
  version: 2

  build-on-pr:
    jobs:
      - build-and-save:
          matrix:
            parameters:
              architecture: [amd64, arm64]
      - push-multi-arch:
          requires: [build-and-save]

  # build-and-push-on-master-push:
  #   jobs:
  #     - build-and-push:
  #         matrix:
  #           parameters:
  #             architecture: [amd64, arm64]
  #         filters:
  #           branches:
  #             only:
  #               - master

  # build-and-push-weekly:
  #   # Rebuild periodically rather than based on git changes.
  #   triggers:
  #     - schedule:
  #         # Run at 07:00 every Thursday, UTC.
  #         cron: "0 07 * * 4"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #               - main

  #   jobs:
  #     - build-and-push:
  #         matrix:
  #           parameters:
  #             architecture: [amd64, arm64]
  #         # Run only on these branches (each pushing different images)
  #         filters:
  #           branches:
  #             only:
  #               - master
  #               - main
