#
# Rebuild and publish our base Docker images for OCaml once a week.
#

version: 2.1

executors:
  amd64:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: medium
  arm64:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: arm.medium

jobs:
  push-multi-arch:
    machine:
      image: ubuntu-2204:2022.07.1
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Load images
          command: |
            for filename in /tmp/workspace/image-*.tar; do
              docker load -i $filename
            done
      - run:
          name: Create and push multi-arch manifest
          command: |
            for image in $(cat pushme); do
              manifest_args=()
              for digest_json in /tmp/workspace/image-*.json; do
                for digest in $(jq -r "map(select(.RepoTags | contains([\"$image\"])) | .Id) | unique | .[]" < $digest_json); do
                  manifest_args+=( --amend $digest )
                done
              done
              docker manifest create $image $manifest_args
            done

  build-and-save:
    parameters:
      architecture:
        type: executor
    executor: << parameters.architecture >>
    steps:
      - checkout
      - run:
          name: Build
          command: make build
      - run:
          name: Save images
          command: |
            docker image inspect > images-<< parameters.architecture >>.json
            docker save -o images-<< parameters.architecture >>.tar $(cat pushme)
      - persist_to_workspace:
          root: .
          paths:
            - images-<< parameters.architecture >>.tar
            - pushme
            - images-<< parameters.architecture >>.json

  build-only:
    parameters:
      architecture:
        type: executor
    executor: << parameters.architecture >>
    steps:
      - checkout
      - run:
          name: Build
          command: make build

workflows:
  version: 2

  build-on-pr:
    jobs:
      - build-and-save:
          matrix:
            parameters:
              architecture: [amd64, arm64]
      - push-multi-arch:
          requires: [build-and-save]

  # build-and-push-on-master-push:
  #   jobs:
  #     - build-and-push:
  #         matrix:
  #           parameters:
  #             architecture: [amd64, arm64]
  #         filters:
  #           branches:
  #             only:
  #               - master

  # build-and-push-weekly:
  #   # Rebuild periodically rather than based on git changes.
  #   triggers:
  #     - schedule:
  #         # Run at 07:00 every Thursday, UTC.
  #         cron: "0 07 * * 4"
  #         filters:
  #           branches:
  #             only:
  #               - master
  #               - main

  #   jobs:
  #     - build-and-push:
  #         matrix:
  #           parameters:
  #             architecture: [amd64, arm64]
  #         # Run only on these branches (each pushing different images)
  #         filters:
  #           branches:
  #             only:
  #               - master
  #               - main
