#
# Rebuild and publish our base Docker images for OCaml once a week.
#

version: 2.1

jobs:
  build-and-push:
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout

      # Work around "no docker within no docker".
      - setup_remote_docker:
          # Note that the default version (17.09.0-ce)
          # (see <https://circleci.com/docs/2.0/building-docker-images/#docker-version>)
          # causes issues with permissions inside of the nested docker instances.
          # See e.g., <https://github.com/docker-library/php/issues/1192#issuecomment-902366923>
          version: 20.10.14

      - run:
          name: Build
          command: make build
      - run:
          name: Login
          command: ./.circleci/docker-login
      - run:
          name: Push
          command: make push

  build-only:
    docker:
      - image: cimg/base:current-22.04
    steps:
      - checkout

      # Work around "no docker within no docker".
      - setup_remote_docker:
          # Note that the default version (17.09.0-ce)
          # (see <https://circleci.com/docs/2.0/building-docker-images/#docker-version>)
          # causes issues with permissions inside of the nested docker instances.
          # See e.g., <https://github.com/docker-library/php/issues/1192#issuecomment-902366923>
          version: 20.10.14

      - run:
          name: Build
          command: make build

workflows:
  version: 2

  build-on-push:
    jobs:
      - build-only

  build-and-push-weekly:
    # Rebuild periodically rather than based on git changes.
    triggers:
      - schedule:
          # Run at 07:00 every Thursday, UTC.
          cron: "0 07 * * 4"
          filters:
            branches:
              only:
                - master
                - main

    jobs:
      - build-and-push:
          # Run only on these branches (each pushing different images)
          filters:
            branches:
              only:
                - master
                - main
