#
# Rebuild and publish our base Docker images for OCaml once a week.
#

version: 2.1

executors:
  linux/amd64:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: medium
  linux/arm64:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: arm.medium

jobs:
  build-and-push:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Build
          command: make build
      - run:
          name: Login
          command: ./.circleci/docker-login
      - run:
          name: Push
          command: make push

  build-only:
    parameters:
      platform:
        type: executor
    executor: << parameters.platform >>
    steps:
      - checkout
      - run:
          name: Build
          command: make build

workflows:
  version: 2

  build-on-pr:
    jobs:
      - build-only:
          matrix:
            parameters:
              platform: [linux/amd64, linux/arm64]

  build-and-push-on-master-push:
    jobs:
      - build-and-push:
          matrix:
            parameters:
              platform: [linux/amd64, linux/arm64]
          filters:
            branches:
              only:
                - master

  build-and-push-weekly:
    # Rebuild periodically rather than based on git changes.
    triggers:
      - schedule:
          # Run at 07:00 every Thursday, UTC.
          cron: "0 07 * * 4"
          filters:
            branches:
              only:
                - master
                - main

    jobs:
      - build-and-push:
          matrix:
            parameters:
              platform: [linux/amd64, linux/arm64]
          # Run only on these branches (each pushing different images)
          filters:
            branches:
              only:
                - master
                - main
