#
# Rebuild and publish our base Docker images for OCaml once a week.
#

version: 2.1

jobs:
  build-and-push:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout

      # Work around "no docker within no docker".
      - setup_remote_docker

      - run:
          name: Build
          command: make build
      - run:
          name: Login
          command: ./.circleci/docker-login
      - run:
          name: Push
          command: make push

  build-only:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout

      # Work around "no docker within no docker".
      - setup_remote_docker

      - run:
          name: Build
          command: make build

#
# Build and push a docker image for each change on the main branch and
# weekly.
#
# This occurs after merging a PR or after pushing directly to the main
# branch. We also build an image every week to keep things fresh since
# it updates the list of available opam packages and installs the
# latest version of unpinned packages.
#
# Images get tagged with a date like '2021-04-08'. If multiple images
# get built on the same day, they will overwrite each other, which is
# fine.
#
workflows:
  version: 2
  build-on-master-push:
    jobs:
      - build-and-push:
          filters:
            branches:
              only:
                - master
                - main

  # Check pull requests
  build-on-branch-push:
    jobs:
      - build-only:
          filters:
            branches:
              ignore:
                - master
                - main

  build-weekly:
    # Rebuild periodically rather than based on git changes.
    triggers:
      - schedule:
          # Run at 10:00 every Wednesday, UTC.
          cron: "0 10 * * 3"
          filters:
            branches:
              only:
                - master
                - main

    jobs:
      - build-and-push:
          # Run only on the main branch.
          filters:
            branches:
              only:
                - master
                - main
